// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks_test.go -package=indexer
//

// Package indexer is a generated GoMock package.
package indexer

import (
	postgres "1-task/internal/storage/postgres"
	context "context"
	big "math/big"
	reflect "reflect"
	time "time"

	ethereum "github.com/ethereum/go-ethereum"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockRPCClient is a mock of RPCClient interface.
type MockRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockRPCClientMockRecorder
	isgomock struct{}
}

// MockRPCClientMockRecorder is the mock recorder for MockRPCClient.
type MockRPCClientMockRecorder struct {
	mock *MockRPCClient
}

// NewMockRPCClient creates a new mock instance.
func NewMockRPCClient(ctrl *gomock.Controller) *MockRPCClient {
	mock := &MockRPCClient{ctrl: ctrl}
	mock.recorder = &MockRPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCClient) EXPECT() *MockRPCClientMockRecorder {
	return m.recorder
}

// BlockNumber mocks base method.
func (m *MockRPCClient) BlockNumber(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockNumber indicates an expected call of BlockNumber.
func (mr *MockRPCClientMockRecorder) BlockNumber(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockNumber", reflect.TypeOf((*MockRPCClient)(nil).BlockNumber), ctx)
}

// Close mocks base method.
func (m *MockRPCClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRPCClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRPCClient)(nil).Close))
}

// FilterLogs mocks base method.
func (m *MockRPCClient) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterLogs", ctx, q)
	ret0, _ := ret[0].([]types.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterLogs indicates an expected call of FilterLogs.
func (mr *MockRPCClientMockRecorder) FilterLogs(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterLogs", reflect.TypeOf((*MockRPCClient)(nil).FilterLogs), ctx, q)
}

// HeaderByNumber mocks base method.
func (m *MockRPCClient) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeaderByNumber", ctx, number)
	ret0, _ := ret[0].(*types.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeaderByNumber indicates an expected call of HeaderByNumber.
func (mr *MockRPCClientMockRecorder) HeaderByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeaderByNumber", reflect.TypeOf((*MockRPCClient)(nil).HeaderByNumber), ctx, number)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetIndexerState mocks base method.
func (m *MockRepository) GetIndexerState(ctx context.Context, name string) (postgres.IndexerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexerState", ctx, name)
	ret0, _ := ret[0].(postgres.IndexerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexerState indicates an expected call of GetIndexerState.
func (mr *MockRepositoryMockRecorder) GetIndexerState(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexerState", reflect.TypeOf((*MockRepository)(nil).GetIndexerState), ctx, name)
}

// SaveIndexerState mocks base method.
func (m *MockRepository) SaveIndexerState(ctx context.Context, name string, lastBlock uint64, processedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIndexerState", ctx, name, lastBlock, processedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveIndexerState indicates an expected call of SaveIndexerState.
func (mr *MockRepositoryMockRecorder) SaveIndexerState(ctx, name, lastBlock, processedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveIndexerState", reflect.TypeOf((*MockRepository)(nil).SaveIndexerState), ctx, name, lastBlock, processedAt)
}

// UpsertWithdrawFlow mocks base method.
func (m *MockRepository) UpsertWithdrawFlow(ctx context.Context, flow postgres.WithdrawFlow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWithdrawFlow", ctx, flow)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWithdrawFlow indicates an expected call of UpsertWithdrawFlow.
func (mr *MockRepositoryMockRecorder) UpsertWithdrawFlow(ctx, flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWithdrawFlow", reflect.TypeOf((*MockRepository)(nil).UpsertWithdrawFlow), ctx, flow)
}
