// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: charts.sql

package queries

import (
	"context"
	"time"
)

const listDailyFlowPoints = `-- name: ListDailyFlowPoints :many
SELECT
  date_trunc('day', block_time)::date AS day,
  COALESCE(SUM(CASE WHEN event_type = 'request' THEN amount_normalized::numeric ELSE 0 END), 0)::double precision AS requested,
  COALESCE(SUM(CASE WHEN event_type = 'request' AND amount_normalized > 0 THEN 1 ELSE 0 END), 0)::double precision AS request_count,
  COALESCE(SUM(CASE WHEN event_type = 'withdraw' THEN amount_normalized::numeric ELSE 0 END), 0)::double precision AS withdrawn
FROM raw_withdraw_flows
GROUP BY 1
ORDER BY 1 ASC
`

type ListDailyFlowPointsRow struct {
	Day          time.Time
	Requested    float64
	RequestCount float64
	Withdrawn    float64
}

func (q *Queries) ListDailyFlowPoints(ctx context.Context) ([]ListDailyFlowPointsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyFlowPoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyFlowPointsRow
	for rows.Next() {
		var i ListDailyFlowPointsRow
		if err := rows.Scan(
			&i.Day,
			&i.Requested,
			&i.RequestCount,
			&i.Withdrawn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
