// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: indexer_state.sql

package queries

import (
	"context"
	"time"
)

const getIndexerState = `-- name: GetIndexerState :one
SELECT
  name,
  last_processed_block,
  last_processed_time,
  updated_at
FROM indexer_state
WHERE name = $1
`

func (q *Queries) GetIndexerState(ctx context.Context, name string) (IndexerState, error) {
	row := q.db.QueryRowContext(ctx, getIndexerState, name)
	var i IndexerState
	err := row.Scan(
		&i.Name,
		&i.LastProcessedBlock,
		&i.LastProcessedTime,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIndexerState = `-- name: UpsertIndexerState :exec
INSERT INTO indexer_state (
  name,
  last_processed_block,
  last_processed_time
) VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (name) DO UPDATE
SET
  last_processed_block = EXCLUDED.last_processed_block,
  last_processed_time = EXCLUDED.last_processed_time,
  updated_at = NOW()
`

type UpsertIndexerStateParams struct {
	Name               string
	LastProcessedBlock int64
	LastProcessedTime  time.Time
}

func (q *Queries) UpsertIndexerState(ctx context.Context, arg UpsertIndexerStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertIndexerState, arg.Name, arg.LastProcessedBlock, arg.LastProcessedTime)
	return err
}
