// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"time"
)

type IndexerState struct {
	Name               string
	LastProcessedBlock int64
	LastProcessedTime  time.Time
	UpdatedAt          time.Time
}

type RawWithdrawFlow struct {
	ID               int64
	ChainID          int64
	TxHash           string
	LogIndex         int32
	BlockNumber      int64
	BlockTime        time.Time
	SenderAddress    string
	EventType        string
	AmountRaw        string
	AmountNormalized string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CooldownEndAt    int64
}
